### ISSUE TITLE
Incident creation on vulnerabilities 

### ISSUE THREAD

**Issue by PekkaJalonen** [misje/opencti-wazuh-connector#42]
Hi,

Thanks for a great effort you have put on developing this connector. And sorry for un-formal issue.

I tested 0.2.1 with docker and was able to enrich vulnerabilities, but I cannot get incident creation to work. Has it even been implemented for vulnerabilities?

I followed the docs in detail, and checked that incident creation is enabled and indicator is not required, but i just get the sightings, but no incident. Tested with per-query.

Also, it would be a great addition to have incident creation mode per-system.

**Comment by misje** [comment]
Hei,

Thank you very much for testing! Yes, every single entity has been tested. Vulnerabilities as well. It sounds to me that you may need to configure [ vulnerability_incident_cvss3_score_threshold](https://misje.github.io/opencti-wazuh-connector/config_reference.html#wazuh.config.Config.vulnerability_incident_cvss3_score_threshold), which by default is disabled in order to not flood you with alerts (depending on your sources, agents and patching procedures). Tell me if that helps you. 

I see now that it is confusing that this setting is separate from the other "create_incident_" settings. I will work on that in the docs. Any suggestions are very welcome.

Note that I added two changes to *dev* today that may be relevant as well:

- If CVSS3 score is not present, but CVSS3 severity is, severity is used as a fallback when determining whether the score meets the aforementioned threshold
- If the vulnerability does no contain a published date, this no longer causes an exception

**Comment by misje** [comment]
I must also note that I have only just recently begun running tests with plenty of real-world *real-time* IoCs, which presents a number of challenges in terms of noise. I'm focusing on addressing this going forward with the project.

**Comment by misje** [comment]
After some more testing, I believe there may still be a bug in the logic that determines whether a vulnerability should cause an incident or not. I'll investigate.

**Comment by misje** [comment]
The bug should be fixed now.

**Comment by misje** [comment]
![2024-06-01_12-50](https://github.com/misje/opencti-wazuh-connector/assets/4006538/dc0f3b5e-f418-4150-9024-2b0b941c50ff)

The documentation is now updated with a reference to the setting required for vulnerability incident creation. It will published on the next release. I hope this solves your issue, along with the aforementioned fixes. Feel free to reopen the issue if you still experience issues.
